# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsistencyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('type_en_us', models.CharField(max_length=20, null=True, verbose_name='type')),
                ('type_pt_br', models.CharField(max_length=20, null=True, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Level of consistency',
                'verbose_name_plural': 'Levels of consistency',
            },
        ),
        migrations.CreateModel(
            name='Discretization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='type')),
                ('type_en_us', models.CharField(max_length=30, null=True, verbose_name='type')),
                ('type_pt_br', models.CharField(max_length=30, null=True, verbose_name='type')),
                ('pandas_code', models.CharField(max_length=20, verbose_name='pandas code')),
            ],
            options={
                'verbose_name': 'Discretization',
                'verbose_name_plural': 'Discretizations',
            },
        ),
        migrations.CreateModel(
            name='OriginalSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_file_source', models.DateTimeField(auto_now_add=True, verbose_name='date and time')),
                ('temporal_serie_id', models.IntegerField()),
                ('consistency_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ConsistencyLevel', verbose_name='level of consistency')),
                ('discretization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Discretization', verbose_name='discretization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'Original Serie',
                'verbose_name_plural': 'Original Series',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.CreateModel(
            name='TemporalSerie',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('data', models.FloatField(null=True, verbose_name='data')),
                ('date', models.DateTimeField(verbose_name='date and time')),
            ],
            options={
                'verbose_name': 'Temporal Serie',
                'verbose_name_plural': 'Temporal Series',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Metric Unit',
                'verbose_name_plural': 'Metric Units',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=20, verbose_name='variable')),
                ('variable_en_us', models.CharField(max_length=20, null=True, verbose_name='variable')),
                ('variable_pt_br', models.CharField(max_length=20, null=True, verbose_name='variable')),
                ('ana_code', models.CharField(max_length=2, verbose_name='ANA code')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.AlterUniqueTogether(
            name='temporalserie',
            unique_together=set([('id', 'date')]),
        ),
        migrations.AddField(
            model_name='originalserie',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Unit'),
        ),
        migrations.AddField(
            model_name='originalserie',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Variable', verbose_name='variable'),
        ),
        migrations.AddField(
            model_name='discretization',
            name='stats_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stats', verbose_name='stats type'),
        ),
    ]
