# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            options={
                'verbose_name': 'Coordinate',
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Coordinate', verbose_name='coordinates')),
            ],
            options={
                'verbose_name': 'Localization',
                'verbose_name_plural': 'Localizations',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Localization', verbose_name='localization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Station type',
                'verbose_name_plural': 'Station Types',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.StationType', verbose_name='station type'),
        ),
    ]
